### PR TITLE
Fix/paxdetails

### LINKED ISSUE #278: Passenger Details | PNR Tab, Add trip type to itinerary header

### PR DESCRIPTION
**Pull request by kasimhelil**
Resolves #278 and #279

### CODE REVIEW

**Comment by kasimhelil** [comment]
This also resolves #242

**Review by gtasautumn — CHANGES_REQUESTED** [review]
Good, but the link that navs you back to the flightpax page doesn't provide the data for the sidenav component. Took me a minute to trace the issue because I put the logic in the wrong place when I built it for the link from flights to flightpax.

From flights, the link only describes the uri for flightpax in the headers definition for the table component, but the **Table passes all the data for the sidenav**. See lines 260 - 264 in Table:

`onClick={() =>`
`   navigate(sendRowToLink, {`
           **state: { data: row.original }**
`   })`
`}`

Sooo, I need to refactor this because is confusing to have it inside Table and hard to find when there's a problem. For now, we need to pull together that data from paxdetail and include it in the link as state data.

**Comment by kasimhelil** [comment]
> Good, but the link that navs you back to the flightpax page doesn't provide the data for the sidenav component. Took me a minute to trace the issue because I put the logic in the wrong place when I built it for the link from flights to flightpax.
> 
> From flights, the link only describes the uri for flightpax in the headers definition for the table component, but the **Table passes all the data for the sidenav**. See lines 260 - 264 in Table:
> 
> `onClick={() =>`
> ` navigate(sendRowToLink, {`
> **state: { data: row.original }**
> ` })`
> `}`
> 
> Sooo, I need to refactor this because is confusing to have it inside Table and hard to find when there's a problem. For now, we need to pull together that data from paxdetail and include it in the link as state data.

- It should be good now. The back end was returning 0 for passenger count, so I have made a small change there as well. 
- Also, I added a one line code change on select input, which will resolve #247

**Comment by gtasautumn** [comment]
We need the flight history fix on the PNR tab as well.

**Comment by kasimhelil** [comment]
I couldn't get flight direction work for flight legs. If you click on one of the flights numbers under  `Flight History -> Total flight history`, you can see flight direction is not displayed on the side nav. I will create a ticket for it.

**Comment by kasimhelil** [comment]
> I couldn't get flight direction work for flight legs. If you click on one of the flights numbers under `Flight History -> Total flight history`, you can see flight direction is not displayed on the side nav. I will create a ticket for it.

May be,  it make sense for flight legs not to have direction

**Comment by tjwdev** [comment]
Flight legs having direction does not always make sense. Direction is related to the host country, flight legs can often deal with legs of travel that exist between countries that are NOT the host country. Inbound/Outbound makes no sense in those cases. However, for things like round trips we'll be able to see clearly that a border crossing event for the host country WILL occur again, but we deal with flight legs generically and don't consider inbound/outbound because of the above. We eventually capture that particular leg as a border crossing event however as it comes in as a new message.

Not all flight legs can have direction, this is certain, is it worthwhile to add direction to flight legs that we can infer the direction of? I'm not sure of the use case, but it's certainly possible to get that information some of the time if required.

**Comment by gtasautumn** [comment]
We should probably discuss with Dave before making further changes.

- **Total Flight History** contains both prime flights, which do have a direction, and booking details, but its populating that data as bookingdetails, which it probably should not. Ideally, we populate the data as flight data and leave the direction null for booking details. See **passengerdetailscontroller>copyBookingDetailFlightModelToVo**
- **Current Itinerary** should probably have the links removed for now. When there's more than one leg, the bookingdetail legs have no id to give the link, so it comes up **gtas/flightpax/null**. When there is a link, it's the same flight we're already on.
- The current flight in both History and Current should probably not have a link for bookingdetail records. Do we ever receive passenger lists for these?

Also, the 8080 Flight History links back to the paxdetail, not the flightpax. I am ok with it being different if that makes sense to everyone.

To rehash an old rant, it really isn't a great design to have booking details a completely separate entity from flights. They are all flights (or flight legs). It would simplify things store them as modified flights or an entity that inherits from the same parent with direction of "External" or something.

**Comment by kasimhelil** [comment]
> We should probably discuss with Dave before making further changes.
> 
> * **Total Flight History** contains both prime flights, which do have a direction, and booking details, but its populating that data as bookingdetails, which it probably should not. Ideally, we populate the data as flight data and leave the direction null for booking details. See **passengerdetailscontroller>copyBookingDetailFlightModelToVo**
> * **Current Itinerary** should probably have the links removed for now. When there's more than one leg, the bookingdetail legs have no id to give the link, so it comes up **gtas/flightpax/null**. When there is a link, it's the same flight we're already on.
> * The current flight in both History and Current should probably not have a link for bookingdetail records. Do we ever receive passenger lists for these?
> 
> Also, the 8080 Flight History links back to the paxdetail, not the flightpax. I am ok with it being different if that makes sense to everyone.
> 
> To rehash an old rant, it really isn't a great design to have booking details a completely separate entity from flights. They are all flights (or flight legs). It would simplify things store them as modified flights or an entity that inherits from the same parent with direction of "External" or something.

I completely agree! As @gtasautumn said , we need  a clear and consistent design for for all entities used  on pax details, including `booking details/flight legs`, which we will do when we start a backend clean up.
- I saw the 8080 Flight History (it is also mentioned on the ticket), but does it make sense to have a link on Flight Number to a single pax details? For me it is miss leading, and since we are already on pax details, it is unnecessary. The only way it would make sense to me is if it takes me to flight pax.
 - For now removing the links on Flight history makes more sense, I think. We can bring it back later after redesigning the backend

**Let me know what you think and I will make the changes**

**Comment by gtasautumn** [comment]
Yeah, go ahead and remove the links on flight history. We can discuss the rest later, thx.

**Review by gtasautumn — APPROVED** [review]

**Comment by kasimhelil** [comment]
We don't need the backed change anymore; I will remove the backend PR

**Pull request merged**
