### PR TITLE
Fix/paxdetails

### LINKED ISSUE #479: PNR Segment Title
Append the text "Reservation Number" before the record locator number

### PR DESCRIPTION
**Pull request by kasimhelil**
Resolves #479 #478 #477 #470 #449

### CODE REVIEW

**Review by gtasautumn — CHANGES_REQUESTED** [review]
For #470 , spinner on reload, let's pull this fix out of the current PR. 

For this one, it makes the entire content area reload/flash when ideally the sidenav and tabs should remain but have a separate spinner overlay within the sidenav itself. The PNR tab data is the same for all co-travelers so it doesn't need to actually refresh (though the other tabs might). It is also attempting to refetch all the data for all the paxdetail child tabs, which is unnecessary.

I think it makes sense to separate this one out and possibly pair it with the planned fix to break the tabs out into separate endpoints. But we can discuss.

**Review by gtasautumn — CHANGES_REQUESTED** [review]
Please add the link to flightPax to the FlightBadge as well.

**Comment by kasimhelil** [comment]
Removed the spinner and added link on flight badge
- There is a small change on the backend as well

**Review by gtasautumn — APPROVED** [review]
looks good

**Pull request merged**
