### PR TITLE
User registration

### PR DESCRIPTION
**Pull request by kasimhelil**
Please get the latest for the backend and update your db if you test this locally!

### CODE REVIEW

**Comment by gtasautumn** [comment]
getting this error in commons tests:


[INFO] Running gov.gtas.services.SignupRequestServiceTest                                                                                               [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.01 s <<< FAILURE! - in gov.gtas.services.SignupRequestServiceTest             [ERROR] initializationError(gov.gtas.services.SignupRequestServiceTest)  Time elapsed: 0.009 s  <<< ERROR!                                              org.mockito.exceptions.base.MockitoException:                                                                                                                                                                                                                                                                                                                                                                                                                           No tests found in SignupRequestServiceTest                                                                                                              Is the method annotated with @Test?                                                                                                                     Is the method public?                                                                                                                                                                                                                                                                                           Caused by: java.lang.reflect.InvocationTargetException                                                                                                  Caused by: org.junit.runners.model.InitializationError
--

**Comment by kasimhelil** [comment]
Please skip the unit tests when you build, I forgot to add a unit test for the service class, I will do tonight or maybe tomorrow morning!

**Comment by gtasautumn** [comment]
I deleted the file locally to build. The usual skipTest and skipUnitTests commands don't work for me.

**Comment by gtasautumn** [comment]
when I ran this last night, everything worked but the emails. I kept getting 500 errors. Am I missing something?

**Comment by kasimhelil** [comment]
- Did you set up the **email service properties** on application.properties file? 
- You should also have an email for your users (for those who can receive sign up email notification)

**Pull request merged**
