### PR TITLE
Fix/translation fetch

### LINKED ISSUE #672: Translations not working
**Describe the bug**
The edit mode translations are saving in the database and can be seen on the Language Editor page, but the actual translatable fields on the page are not being translated anymore. This is reproducible on dev only, not locally.

**To Reproduce**
1. As an admin (dev env), go to the language editor page
2. Click on Live Edit
3. Edit any editable text on the page and save
4. Observe that when the page reloads, it does not reflect the page
5. Page through the table results of edits for the edit you just made
6. Observe that the change is reflected there, meaning it did save to db.

**Expected behavior**
The page should be updated with all live edit changes for the applicable language.

**Notes**
In dev tools > networking tab, the fetch for the page translations appears to be returning javascript rather than the expected json. The request header also does not have the "router" tag appended, though it is using the same base header configs as most other calls to the backend.

### PR DESCRIPTION
**Pull request by gtasautumn**
Fixes #672 - Translations not working in dev.

**Update your deps with npm/yarn install if running locally**

Issue was that the translation dependency, i18next, required us to bypass the existing fetch abstraction in servicewrapper, which has the correct header information for all calls, but it was stripping out the additional headers required by our backend in the dev environment. The result was that translation calls made by i18next were not correctly routed to the controller, so frontend never received the codes for translation.

I basically replaced all plugins with my own implementation since they were all causing issues with language resolution, repeat fetch attempts, etc, but that involved updating aspects of the existing context structure, maintaining the state of the last translation load attempt, and handling translation reloads manually.

**To Test**
 1. As admin, go to the language editor page and click the "Live Edit" checkbox
 2. Ensure that the page refreshes and remains in live edit mode
 3. make some obvious edits in your current language and save
 4. Observe that the page refreshes and displays your edits as expected

**To Test Locally**
This will help identify issues before deploying to dev
 1. Login in chrome in an **incognito** window.
 2. Open devtools > networking tab and go to the login page
 3. Observe that your network traffic (XHR) contains a request to /translation/[your_language_code] with a 302 response, followed by a second request to login.html with a 404 response (see the blue highlight)
 3. Login
 4. Observe that your latest network traffic looks like the green highlight - should be a successful second request to /translation/[your_langage_code]
5. Click on the latest request to /translation/[your_language_code] and verify that the request header contains the "router: 'api'" attribute.

translationFetchNetwork

You can also try various combinations of different users, browsers, and deleting any of the browser cache for this site (cookies, local storage, session storage, indexeddb, etc.

**Please note the following:**
* Firefox incognito is not currently supported by indexeddb, and will cause the site to behave unpredictably.
* Deleting the site cookie data can force a logout
* Deleting indexeddb can trigger exceptions that require a page refresh as the browser finalizes the delete

With the exception of firefox incognito, the translations should behave as expected once the page has been stabilized with a refresh or logout.

### CODE REVIEW

**Review by kasimhelil — COMMENTED** [review]
After making a change, the page refreshes, but it doesn't display the changes I have made
Screen Shot 2021-03-03 at 5 36 04 PM

**Comment by gtasautumn** [comment]
Did you update your dependencies? Just tested and its working for me local, not sure what the delta is.

**Comment by kasimhelil** [comment]
> Did you update your dependencies? Just tested and its working for me local, not sure what the delta is.

I found the issue. I don't know if it is a bug or not though. What I did was clicked on the translation tab on the header and checked the language editor's check box. Then, edited the flights and vetting tabs' text and hit submit. When I checked the db, the language was saved as `en` instead of `en-US`, which is the the default on the browser. I edited the language for flights to `en-US` on the db and it worked for that tab.

Screen Shot 2021-03-03 at 9 40 00 PM

**Comment by gtasautumn** [comment]
fixed. Issue was a change in the structure of the language string used as the base language.

**Review by kasimhelil — APPROVED** [review]

**Pull request merged**
