### PR TITLE
Change password

### PR DESCRIPTION
**Pull request by kasimhelil**
- To test this PR locally, please pull the latest for the backend

### CODE REVIEW

**Comment by kasimhelil** [comment]
I was able to reproduce the issue. If you comment out `checkPasswordMatch();` from both  `onConfirmPasswordChange` and `onNewPassChange` functions, it would work as expected.  However, I don't know why this is happening.

The reason I was checking for password match is to change the border color of the **second new password** field as a feedback for the user's input.

 My first attempt was not to allow to submit if the passwords do not match, instead display an error message using a tooltip next to the input fields as what I have seen most of the time, but I failed.  Once I hit `Submit`, the form will send the request; 
I could have checked this inside **Form** component and prevent it. But,  I love how generic the form component is and hesitated to add codes specific to a single component.
Any suggestion?

**Comment by gtasautumn** [comment]
I agree we should keep the form generic, thanks. I think I see a problem. You are storing state data in a ref variable that is not being used as a ref. If you need a reference to a component, you have to set the ref property on the component to the ref variable like:
  `<FooComponent ref={refVariable}`

Once you have that, refVariable.current is the current state, but line 21 will cause issues since you are then setting the state object to a boolean:
   `confirmedRef.current = confirmedPasswordRef.current === newPasswordRef.current;`

I think you can convert all 3 refs to regular state variables like you have for **errorMessage** and it should work without the weird side effects. I will check back later tonight and play with it if you are still having issues.

**Comment by kasimhelil** [comment]
Thanks, I will try that!

**Comment by gtasautumn** [comment]
ready to test?

**Comment by kasimhelil** [comment]
Yes, _there is a known bug though_! (I don't know if it is a good thing, but when you re-enter the password on the confirmation field, once the passwords much, it stops accepting the user input till the user click on the input filed again!

**Comment by kasimhelil** [comment]
Using **useState** sometimes get tricky;  It requires the component to re-render to apply the changes on the current state which I think is related to closure. That's why I have  **useEffect** with all inputs as dependency!

**Pull request merged**
