### PR TITLE
Audit log fixes

### LINKED ISSUE #428: Audit Log - action type bugs
- ACCESS_INFORMATION type missing from dropdown
- action types in the dropdown should be sorted alphabetically
- can't run a query without an action filter even though the page loads without one (selection is required after the first fetch)
- changing type to ALL_ACTIONS returns no data. We could just replace this option with an empty "Select" option since excluding the action filter does what the ALL_ACTIONS option is supposed to do anyway.
- time part of the date filter doesn't work
- data isn't sorted chronologically. Should default to date descending. Thought we fixed that already?
- Any reason we don't filter on the other fields?

### PR DESCRIPTION
**Pull request by tjwdev**
Sister front-end PR for AuditLogFixes branch on GTAS-UI
Fixes #428
-Pulled actions from enumerated list
-Fixed dates not working
-Fixed ALL_ACTIONS showing up and working correctly
-Removed base "Select Action" from drop down
-Merged Kasim's changes for re-adding OrderBy for the search call.

### CODE REVIEW

**Comment by tjwdev** [comment]
Hold off on merging this and its back end; Will incorporate ErrorLog fixes in this as well #429 due to similarities

**Comment by tjwdev** [comment]
This now additionally resolves #429

**Comment by kasimhelil** [comment]
I changed the base branch to `dev`

**Comment by tjwdev** [comment]
Thanks Kasim! Also, I've now merged the conflicts on the branch (and removed erroneous test collection of values from auditlog.js)

**Review by kasimhelil — APPROVED** [review]
Looks good to me!

**Review by gtasautumn — APPROVED** [review]

**Pull request merged**
