### PR TITLE
Feature/rules

### LINKED ISSUE #60: Rules - modal doesn't launch on the first click

### PR DESCRIPTION
**Pull request by gtasautumn**
Fix #60 #61 #63 and misc associated bugs. 
Save, Clear, Run, Delete buttons now work for Rules and Queries
Rules tabs are now filtering correctly
QRModal triggers data refresh on any DB action (not Cancel or clicking out of the modal)

### CODE REVIEW

**Comment by gtasautumn** [comment]
Need to consider a way back from the query details page to the query or rules page that launched it.
Need's the global confirmation component (TBD).

**Comment by gtasautumn** [comment]
1. That's a bug. I think it's a nice feature to allow the users to run the query before deciding whether to save it. The modal just needs to package the conditions and pass them to the details page. I will fix that, thx.

2. This is a known issue. There are probably dozens of select list enums for the entity properties. I am not sure yet the best way to manage them, so it will be handled in a separate ticket. For now the value fields (including dates) are raw text inputs.

**Comment by kasimhelil** [comment]
- Running a query before saving it works! However, I will lose the query once I run it ( I have to type it again to save it). 
May be when we solve the issue to switch between query and querydetail page, this will also be solved.

- QRModal triggers api call when clicking on Cancel (X) button and clicking out of the modal. 
-- This wasn't expected, I think. ( **QRModal triggers data refresh on any DB action (not Cancel or clicking out of the modal)**)

Other than that, it looks good to me 👍

**Comment by gtasautumn** [comment]
1. yes, you have to re-enter the query/rule for now. There is no way currently to get back to the previous page with the unsaved conditions auto-populated in the QB control. The original page launches a new tab in the browser, but that's not how we will handle it here.

2. will fix.

**Comment by gtasautumn** [comment]
shd be fixed now along with another new bug where the table sometimes duplicates itself (?!?!) after a save/delete. pls test for that, I am not super sure how it happened.

**Comment by kasimhelil** [comment]
1.  Trying to save a **rule** with the **enable** button is unchecked will throw an error.
2. **COLSE**, **DELETE**, and **SAVE**  won't close the modal (It was working on the previous change)
3.  **Create new rule** button, doesn't trigger the modal on first attempt. 
 -- Choose _**Rules**_ from **Tools**' dropdown, the click on **Create new rule**. On first click,  the modal won't pop-up 
we can create a ticket for 2 and 3 once 1 is fixed and merge the branch.

**Comment by gtasautumn** [comment]
Found the issues, first looks like a bad merge somewhere. Others caused by unexpected nulls which I didn't see in my local DB and by and tab losing state unexpectedly.

Merged dev (formCallback updates) into feature/rules. 
Fixed non-standard form callback in queries
Fixed broken Table component header definition in Rules - this was breaking the form response to Save, CLose, etc buttons.
Bonus - fixed the page tab switching to "my" when you launch the modal. It now stays on whichever tab was previously selected (all rules or my rules), and only updates when the tabs are clicked.

All shd be fixed.

**Pull request merged**
