### PR TITLE
Password validation

### PR DESCRIPTION
**Pull request by kasimhelil**
- The form component is able to validate inputs before submitting the form,  if  a `validateInputs` function is passed as a prop
-  Validate password inputs (password criteria and match between new password and confirmed password) before submitting the form
- display password criteria on change password pages

### CODE REVIEW

**Comment by gtasautumn** [comment]
Couple of things.

- The two change password forms are out of sync. The page has a 3rd input for the old password, but the modal only has the two "new password" inputs. This is a good argument for only using one. I think we should use the modal in both places, but add the "old password" input to it.
- The inputs do not indicate missing requirements or mismatched passwords until after you click submit. We should highlight the field on lose focus or as they type to show this.

**Comment by kasimhelil** [comment]
> Couple of things.
> 
> * The two change password forms are out of sync. The page has a 3rd input for the old password, but the modal only has the two "new password" inputs. This is a good argument for only using one. I think we should use the modal in both places, but add the "old password" input to it.
> * The inputs do not indicate missing requirements or mismatched passwords until after you click submit. We should highlight the field on lose focus or as they type to show this.

- We  removed the old password input from the modal because admin does not know the users' password. But when users change their own  password, they are required to enter the old one. 
- I think making both modal makes sense to be consistent
-  I don't know why I removed field validation as the user type, especially for the confirm password input (I will add it back)

**Comment by gtasautumn** [comment]
> * We  removed the old password input from the modal because admin does not know the users' password. But when users change their own  password, they are required to enter the old one.

I see. This exposes a security issue tho. The admin can also change his own password without entering the old password via the Manage Users grid, which means if he walks away with the session still open, his account can be hijacked by anybody.

Some systems have the admins enter their current password before making high-level changes. We could consider that for future. **For now, you are right.** Changing another user's password should **not** require an old password, but we have to ensure no logged-in user can change his own password without entering the old password first.

**Comment by gtasautumn** [comment]
looks good

**Review by gtasautumn — APPROVED** [review]

**Pull request merged**
