### PR TITLE
Fix/datepicker layout

### PR DESCRIPTION
**Pull request by gtasautumn**
Trying this again #642 . I ended up putting in a separate media rule for each datepicker input on the Vetting Audit and Error log pages, so its not an elegant solution. It uses set the bottom param until the viewport height is big enough for the years display, then it uses top: auto. Pls screenshot any issues you have and ping me if you have a cleaner solution.

dtpheight1

dtpheight2

### CODE REVIEW

**Review by kasimhelil — COMMENTED** [review]
Now the issue is the top parameter. For a height less than `400px`, the top part of the calendar will be hidden. I think we should disable the calendar modal after a certain height and width, and have just the input field and make the user manually inter the values, just like start and end date on add rule modal.
Screen Shot 2021-03-03 at 11 07 54 PM

**Comment by gtasautumn** [comment]
Yeah, I was actually ok with that. Screen heights that small are outside the standard viewport sizes for most media, even cell phones. We can set a min height for the main container, but I am not sure we ever need to hide the calendar because of a height condition.

**Comment by gtasautumn** [comment]
Pushed a commit to adjust the overall dimensions for all displays (years, months, days, etc) and adjusted the anchor points when adjusting the viewport height so there's no more jumping to the top or bottom. It stops the calendar at the container top so it doesn't get clipped, but it allows the window to clip it when the height is below a certain height, which is fine.

**Review by kasimhelil — APPROVED** [review]
It looks good now!

**Pull request merged**
