### PR TITLE
Small fix to datetimepicker range used for Audit/Error log.

### PR DESCRIPTION
**Pull request by tjwdev**
-We're replacing this soon I believe, but it didn't actually update the date-range, making testing impossible.

### CODE REVIEW

**Review by gtasautumn — COMMENTED** [review]
@kasimhelil will this change be required after your ticket goes in?

**Comment by tjwdev** [comment]
I imagine it won't be, but it's literally impossible to get a different date range that wasn't baseline because the filter wasn't getting updated.

**Comment by gtasautumn** [comment]
yeah, I think that got reported a few days ago on vetting. good enough, let
me test it.

**Comment by kasimhelil** [comment]
No, we will have a new component, and I am going to delete the old one

**Comment by gtasautumn** [comment]
ok, will merge this now just for grins. It won't live much longer.

**Pull request merged**
