### PR TITLE
Datetime picker

### PR DESCRIPTION
**Pull request by kasimhelil**
You can test this on **Error Logs** side nav. That's the only place I've made changes. 
If you think this library is good enough to be added to our project, I can make the other changes.

- There is more to be done on styling

### CODE REVIEW

**Comment by gtasautumn** [comment]
I like this one, but we should use the one that includes the time as well so we can replace the old component everywhere. https://github.com/wojtekmaj/react-datetime-picker
There is an issue with the GUI we should run by Dave before we move ahead, but otherwise it's good for me.

**Comment by kasimhelil** [comment]
Sounds good!

**Comment by gtasautumn** [comment]
moving this to draft until you are ready for review again.

**Comment by kasimhelil** [comment]
I needed to remove the node_modules folder and run yarn install when I switched from  another branch

**Comment by gtasautumn** [comment]
there are some deps that had their versions restricted. Looking at the
compare now. One that might be an issue is the context ponyfiller ...

Did just running install not work?

**Comment by gtasautumn** [comment]
Also, what's the associated ticket for this PR? Do we need to create it?

**Comment by kasimhelil** [comment]
Oh, I thought removing the node module folder won't create any problem. 
I didn't try to run yarn install without removing the node modules. 

- #148 and #213 are the associated tickets, I think

**Comment by kasimhelil** [comment]
Fixed filter form issues related to reset to default

**Review by gtasautumn — APPROVED** [review]
looks good

**Pull request merged**
