### PR TITLE
Fix/watchlist data validation

### LINKED ISSUE #531: Tools - Add Watchlist Import - data not refreshing on import
Successful imports return a 500 error and do not trigger the grid data refresh or the success notification.

### PR DESCRIPTION
**Pull request by gtasautumn**
Fixes #531 

Fixed the success toast so it shows next to the fab button on successful adds/edits/imports
Data refreshes on all updates
Fixed the 500 error on submit
Made all form fields required and validate all records before uploading

The toast isn't pretty yet. Gonna push that change in a separate ticket.

### CODE REVIEW

**Comment by gtasautumn** [comment]
Need to PR this one after #538. Or I can rebase it off of dev.

**Review by tjwdev — APPROVED** [review]
LGTM, will merge after #538 merge

**Comment by tjwdev** [comment]
There is a small conflict after merging #538 fix, if you could please resolve. Thank you!

**Comment by gtasautumn** [comment]
done

**Review by tjwdev — APPROVED** [review]
LGTM

**Pull request merged**
