### PR TITLE
Fix/import watchlist

### PR DESCRIPTION
**Pull request by kasimhelil**

### CODE REVIEW

**Comment by gtasautumn** [comment]
I am getting a 400 error when I try to import. Server returns

`Parse error for values [6/7/1975,] with type date for 'Engine Rule Creation'.`

The issue seems to be that when you use excel, it reformats the date to mm/dd/yyyy, which does not get reformatted before getting passed to the backend. I tried it with a single hand-typed row as well as altering an export of the existing valid records, and neither worked.

There is also an extra partial record being sent to the backend. It doesn't seem to be related to the error tho:

importwl

**Comment by kasimhelil** [comment]
I can reformat "mm/dd/yyyy" to "yyyy-mm-dd" before we try to save the watchlist. My concern is that excel might convert the exported data  to other formats on different machine. 
- I will have a temp fix for now; however we should revisit this when we work on the backend clean up!

**Comment by gtasautumn** [comment]
as long as the data can be imported as a date, shouldn't matter. Convert it to a date, then handle the format. If its null or can't be converted, skip that row.

We will revisit having to send it to the backend as a string later.

**Comment by kasimhelil** [comment]
- Disabled the calendar on watchlist modal; it doesn't fit good
- Needs to work on the style (the input field width is not same as the other inputs). If you have easy fix for it please, let me know.

**Comment by gtasautumn** [comment]
Fixes #240

**Pull request merged**
